apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 80
  selector:
    service: frontend
#Make the service type as LoadBalancer to access it from Open Internet
  type: LoadBalancer    
